// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATnEwPnkBUROF6UrerG7uYXyqJIpuzBhc',
    appId: '1:596268341739:web:1c28e5917303b4bb0aa1ae',
    messagingSenderId: '596268341739',
    projectId: 'projek-firebase-963f5',
    authDomain: 'projek-firebase-963f5.firebaseapp.com',
    storageBucket: 'projek-firebase-963f5.firebasestorage.app',
    measurementId: 'G-KHRTBCBCW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFX3cmi4BJ_CyEpx7xnrLhrPuMmMBFN5Q',
    appId: '1:596268341739:android:4c005c1f4b26d4ff0aa1ae',
    messagingSenderId: '596268341739',
    projectId: 'projek-firebase-963f5',
    storageBucket: 'projek-firebase-963f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOdVrUkzPyBcw2DH2QvPU3_gZW6rQFxEQ',
    appId: '1:596268341739:ios:8320d07778e658fa0aa1ae',
    messagingSenderId: '596268341739',
    projectId: 'projek-firebase-963f5',
    storageBucket: 'projek-firebase-963f5.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOdVrUkzPyBcw2DH2QvPU3_gZW6rQFxEQ',
    appId: '1:596268341739:ios:8320d07778e658fa0aa1ae',
    messagingSenderId: '596268341739',
    projectId: 'projek-firebase-963f5',
    storageBucket: 'projek-firebase-963f5.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATnEwPnkBUROF6UrerG7uYXyqJIpuzBhc',
    appId: '1:596268341739:web:88d331c865fe3f6b0aa1ae',
    messagingSenderId: '596268341739',
    projectId: 'projek-firebase-963f5',
    authDomain: 'projek-firebase-963f5.firebaseapp.com',
    storageBucket: 'projek-firebase-963f5.firebasestorage.app',
    measurementId: 'G-CGL412XHSP',
  );
}
